version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: rent_a_house
    ports:
      - 5432:5432
    #volumes:
    #  - C:/dev/data:/var/lib/postgresql

  rent-a-house-app:
    container_name: rent-a-house
    build:
      context: .
      dockerfile: Dockerfile
    image: rent-a-house:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    working_dir: /tena-a-house
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/rent_a_house
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update