version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rent_a_house
    ports:
      - 15432:5432
    volumes:
      - C:/dev/data:/var/lib/postgresql